# k8s/keycloak/keycloak-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
  namespace: twojkwadrat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi