services:
  frontend:
    image: nowsiejko/twojkwadrat-frontend:latest
    restart: unless-stopped 
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next       
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
    depends_on:
      py-backend:
        condition: service_healthy
      go-backend:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - frontend_backend

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://mysql:3306/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=${MYSQL_PASSWORD}  
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - db_backend


  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      # - MYSQL_DATABASE=
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - db_backend
      - frontend_backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 2


  py-backend:
    image: nowsiejko/twojkwadrat-py-backend:latest
    restart: unless-stopped
    command: python -m uvicorn main:app --host 0.0.0.0 --port 5000 --reload

    ports:
      - "5000:5000"

    environment:
    - KEYCLOAK_URL=http://keycloak:8080
    - KEYCLOAK_REALM=TwojKwadrat
    - KEYCLOAK_CLIENT_ID=TwojKwadrat-app
    - DB_HOST=mysql
    - DB_PORT=3306
    - DB_USER=keycloak
    - DB_PASSWORD=${MYSQL_PASSWORD}
    - DB_NAME=keycloak
    - DB_POOL_NAME=keycloak_pool
    - DB_POOL_SIZE=5
    depends_on:
      keycloak:
        condition: service_started
      mysql:
        condition: service_healthy
    networks:
      - frontend_backend
      - db_backend
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 5s
      timeout: 3s
      retries: 2


  go-backend:
    image: nowsiejko/twojkwadrat-go-backend:latest
    restart: unless-stopped
    command: ./main
    ports:
      - "5001:5001"
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=TwojKwadrat
      - KEYCLOAK_CLIENT_ID=TwojKwadrat-app
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=posts
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      keycloak:
        condition: service_started
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - frontend_backend
      - db_backend
      - mq-backend

    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:5001/health"]
      interval: 5s
      timeout: 3s
      retries: 2

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     
      - "15672:15672" 
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq 
      
    networks:
      - mq-backend
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  notification-service:
    image: nowsiejko/notification-service:latest
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - mq-backend


    
volumes:
  mysql_data:
  keycloak_data:
  rabbitmq_data:
  
    

networks:
  frontend_backend:
    driver: bridge 
  db_backend:
    driver: bridge
  mq-backend:
    driver: bridge


