# k8s/storage/mysql-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: twojkwadrat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi