apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: twojkwadrat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0     
      selectPolicy: Max
      policies:
      - type: Pods
        value: 1     
        periodSeconds: 15
      - type: Percent  
        value: 50     
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 60    
      selectPolicy: Max
      policies:
      - type: Pods
        value: 1      
        periodSeconds: 30

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-backend-hpa
  namespace: twojkwadrat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60 
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0      
      selectPolicy: Max
      policies:
      - type: Pods
        value: 2     
        periodSeconds: 15
      - type: Percent
        value: 50    
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 60   
      selectPolicy: Max
      policies:
      - type: Pods
        value: 1    
        periodSeconds: 30

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: py-backend-hpa
  namespace: twojkwadrat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: py-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60 
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0     
      selectPolicy: Max
      policies:
      - type: Pods
        value: 2     
        periodSeconds: 15
      - type: Percent
        value: 50    
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 60    
      selectPolicy: Max
      policies:
      - type: Pods
        value: 1     
        periodSeconds: 30