apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer
  namespace: twojkwadrat
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-loadbalancer
  namespace: twojkwadrat
spec:
  type: LoadBalancer
  selector:
    app: keycloak
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: go-backend-loadbalancer
  namespace: twojkwadrat
spec:
  type: LoadBalancer
  selector:
    app: go-backend
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: py-backend-loadbalancer
  namespace: twojkwadrat
spec:
  type: LoadBalancer
  selector:
    app: py-backend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP