apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: twojkwadrat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "hostpath"
  resources:
    requests:
      storage: 2Gi