# k8s/rabbitmq/rabbitmq-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: twojkwadrat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi