name: CI/CD Pipeline

on:
  push:
    branches: [ main, kubernetes ]

env:
  DOCKER_USERNAME: nowsiejko

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service:
          - name: frontend
            context: ./frontend
            image: twojkwadrat-frontend
          - name: go-backend
            context: ./backend_posts
            image: twojkwadrat-go-backend
          - name: py-backend
            context: ./backend_users
            image: twojkwadrat-py-backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.service.context }}
        push: true
        tags: ${{ env.DOCKER_USERNAME }}/${{ matrix.service.image }}:latest